/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppClipsRouteImport } from './routes/_app/clips'
import { Route as AppDiscoveryRouteImport } from './routes/_app/discovery'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppViralStudioRouteImport } from './routes/_app/viral-studio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClipsRoute = AppClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppViralStudioRoute = AppViralStudioRouteImport.update({
  id: '/viral-studio',
  path: '/viral-studio',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clips': typeof AppClipsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/settings': typeof AppSettingsRoute
  '/viral-studio': typeof AppViralStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clips': typeof AppClipsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/settings': typeof AppSettingsRoute
  '/viral-studio': typeof AppViralStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/clips': typeof AppClipsRoute
  '/_app/discovery': typeof AppDiscoveryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/viral-studio': typeof AppViralStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clips' | '/discovery' | '/settings' | '/viral-studio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clips' | '/discovery' | '/settings' | '/viral-studio'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/clips'
    | '/_app/discovery'
    | '/_app/settings'
    | '/_app/viral-studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clips': {
      id: '/_app/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof AppClipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery': {
      id: '/_app/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio': {
      id: '/_app/viral-studio'
      path: '/viral-studio'
      fullPath: '/viral-studio'
      preLoaderRoute: typeof AppViralStudioRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClipsRoute: typeof AppClipsRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppViralStudioRoute: typeof AppViralStudioRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClipsRoute: AppClipsRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppViralStudioRoute: AppViralStudioRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
