/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppClipsRouteImport } from './routes/_app/clips'
import { Route as AppDiscoveryRouteImport } from './routes/_app/discovery'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppBrandsIndexRouteImport } from './routes/_app/brands/index'
import { Route as AppBrandsBrandIdRouteImport } from './routes/_app/brands/$brandId'
import { Route as AppViralStudioIndexRouteImport } from './routes/_app/viral-studio/index'
import { Route as AppViralStudioIdRouteImport } from './routes/_app/viral-studio/$id'
import { Route as AppViralStudioNewRouteImport } from './routes/_app/viral-studio/new'
import { Route as AppViralStudioQueueRouteImport } from './routes/_app/viral-studio/queue'
import { Route as AppViralStudioBrandsIndexRouteImport } from './routes/_app/viral-studio/brands/index'
import { Route as AppViralStudioBrandsBrandIdRouteImport } from './routes/_app/viral-studio/brands/$brandId'
import { Route as AppViralStudioTemplatesIndexRouteImport } from './routes/_app/viral-studio/templates/index'
import { Route as AppViralStudioTemplatesTemplateIdRouteImport } from './routes/_app/viral-studio/templates/$templateId'
import { Route as AppViralStudioIdItemsItemIdRouteImport } from './routes/_app/viral-studio/$id_.items.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClipsRoute = AppClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIndexRoute = AppBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsBrandIdRoute = AppBrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => AppRoute,
} as any)
const AppViralStudioIndexRoute = AppViralStudioIndexRouteImport.update({
  id: '/viral-studio/',
  path: '/viral-studio/',
  getParentRoute: () => AppRoute,
} as any)
const AppViralStudioIdRoute = AppViralStudioIdRouteImport.update({
  id: '/viral-studio/$id',
  path: '/viral-studio/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppViralStudioNewRoute = AppViralStudioNewRouteImport.update({
  id: '/viral-studio/new',
  path: '/viral-studio/new',
  getParentRoute: () => AppRoute,
} as any)
const AppViralStudioQueueRoute = AppViralStudioQueueRouteImport.update({
  id: '/viral-studio/queue',
  path: '/viral-studio/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppViralStudioBrandsIndexRoute =
  AppViralStudioBrandsIndexRouteImport.update({
    id: '/viral-studio/brands/',
    path: '/viral-studio/brands/',
    getParentRoute: () => AppRoute,
  } as any)
const AppViralStudioBrandsBrandIdRoute =
  AppViralStudioBrandsBrandIdRouteImport.update({
    id: '/viral-studio/brands/$brandId',
    path: '/viral-studio/brands/$brandId',
    getParentRoute: () => AppRoute,
  } as any)
const AppViralStudioTemplatesIndexRoute =
  AppViralStudioTemplatesIndexRouteImport.update({
    id: '/viral-studio/templates/',
    path: '/viral-studio/templates/',
    getParentRoute: () => AppRoute,
  } as any)
const AppViralStudioTemplatesTemplateIdRoute =
  AppViralStudioTemplatesTemplateIdRouteImport.update({
    id: '/viral-studio/templates/$templateId',
    path: '/viral-studio/templates/$templateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppViralStudioIdItemsItemIdRoute =
  AppViralStudioIdItemsItemIdRouteImport.update({
    id: '/viral-studio/$id_/items/$itemId',
    path: '/viral-studio/$id/items/$itemId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clips': typeof AppClipsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/settings': typeof AppSettingsRoute
  '/brands/$brandId': typeof AppBrandsBrandIdRoute
  '/viral-studio/$id': typeof AppViralStudioIdRoute
  '/viral-studio/new': typeof AppViralStudioNewRoute
  '/viral-studio/queue': typeof AppViralStudioQueueRoute
  '/brands/': typeof AppBrandsIndexRoute
  '/viral-studio/': typeof AppViralStudioIndexRoute
  '/viral-studio/brands/$brandId': typeof AppViralStudioBrandsBrandIdRoute
  '/viral-studio/templates/$templateId': typeof AppViralStudioTemplatesTemplateIdRoute
  '/viral-studio/brands/': typeof AppViralStudioBrandsIndexRoute
  '/viral-studio/templates/': typeof AppViralStudioTemplatesIndexRoute
  '/viral-studio/$id/items/$itemId': typeof AppViralStudioIdItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clips': typeof AppClipsRoute
  '/discovery': typeof AppDiscoveryRoute
  '/settings': typeof AppSettingsRoute
  '/brands/$brandId': typeof AppBrandsBrandIdRoute
  '/viral-studio/$id': typeof AppViralStudioIdRoute
  '/viral-studio/new': typeof AppViralStudioNewRoute
  '/viral-studio/queue': typeof AppViralStudioQueueRoute
  '/brands': typeof AppBrandsIndexRoute
  '/viral-studio': typeof AppViralStudioIndexRoute
  '/viral-studio/brands/$brandId': typeof AppViralStudioBrandsBrandIdRoute
  '/viral-studio/templates/$templateId': typeof AppViralStudioTemplatesTemplateIdRoute
  '/viral-studio/brands': typeof AppViralStudioBrandsIndexRoute
  '/viral-studio/templates': typeof AppViralStudioTemplatesIndexRoute
  '/viral-studio/$id/items/$itemId': typeof AppViralStudioIdItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/clips': typeof AppClipsRoute
  '/_app/discovery': typeof AppDiscoveryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/brands/$brandId': typeof AppBrandsBrandIdRoute
  '/_app/viral-studio/$id': typeof AppViralStudioIdRoute
  '/_app/viral-studio/new': typeof AppViralStudioNewRoute
  '/_app/viral-studio/queue': typeof AppViralStudioQueueRoute
  '/_app/brands/': typeof AppBrandsIndexRoute
  '/_app/viral-studio/': typeof AppViralStudioIndexRoute
  '/_app/viral-studio/brands/$brandId': typeof AppViralStudioBrandsBrandIdRoute
  '/_app/viral-studio/templates/$templateId': typeof AppViralStudioTemplatesTemplateIdRoute
  '/_app/viral-studio/brands/': typeof AppViralStudioBrandsIndexRoute
  '/_app/viral-studio/templates/': typeof AppViralStudioTemplatesIndexRoute
  '/_app/viral-studio/$id_/items/$itemId': typeof AppViralStudioIdItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clips'
    | '/discovery'
    | '/settings'
    | '/brands/$brandId'
    | '/viral-studio/$id'
    | '/viral-studio/new'
    | '/viral-studio/queue'
    | '/brands/'
    | '/viral-studio/'
    | '/viral-studio/brands/$brandId'
    | '/viral-studio/templates/$templateId'
    | '/viral-studio/brands/'
    | '/viral-studio/templates/'
    | '/viral-studio/$id/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clips'
    | '/discovery'
    | '/settings'
    | '/brands/$brandId'
    | '/viral-studio/$id'
    | '/viral-studio/new'
    | '/viral-studio/queue'
    | '/brands'
    | '/viral-studio'
    | '/viral-studio/brands/$brandId'
    | '/viral-studio/templates/$templateId'
    | '/viral-studio/brands'
    | '/viral-studio/templates'
    | '/viral-studio/$id/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/clips'
    | '/_app/discovery'
    | '/_app/settings'
    | '/_app/brands/$brandId'
    | '/_app/viral-studio/$id'
    | '/_app/viral-studio/new'
    | '/_app/viral-studio/queue'
    | '/_app/brands/'
    | '/_app/viral-studio/'
    | '/_app/viral-studio/brands/$brandId'
    | '/_app/viral-studio/templates/$templateId'
    | '/_app/viral-studio/brands/'
    | '/_app/viral-studio/templates/'
    | '/_app/viral-studio/$id_/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clips': {
      id: '/_app/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof AppClipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery': {
      id: '/_app/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/': {
      id: '/_app/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AppBrandsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$brandId': {
      id: '/_app/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AppBrandsBrandIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/': {
      id: '/_app/viral-studio/'
      path: '/viral-studio'
      fullPath: '/viral-studio/'
      preLoaderRoute: typeof AppViralStudioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/$id': {
      id: '/_app/viral-studio/$id'
      path: '/viral-studio/$id'
      fullPath: '/viral-studio/$id'
      preLoaderRoute: typeof AppViralStudioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/new': {
      id: '/_app/viral-studio/new'
      path: '/viral-studio/new'
      fullPath: '/viral-studio/new'
      preLoaderRoute: typeof AppViralStudioNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/queue': {
      id: '/_app/viral-studio/queue'
      path: '/viral-studio/queue'
      fullPath: '/viral-studio/queue'
      preLoaderRoute: typeof AppViralStudioQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/brands/': {
      id: '/_app/viral-studio/brands/'
      path: '/viral-studio/brands'
      fullPath: '/viral-studio/brands/'
      preLoaderRoute: typeof AppViralStudioBrandsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/brands/$brandId': {
      id: '/_app/viral-studio/brands/$brandId'
      path: '/viral-studio/brands/$brandId'
      fullPath: '/viral-studio/brands/$brandId'
      preLoaderRoute: typeof AppViralStudioBrandsBrandIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/templates/': {
      id: '/_app/viral-studio/templates/'
      path: '/viral-studio/templates'
      fullPath: '/viral-studio/templates/'
      preLoaderRoute: typeof AppViralStudioTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/templates/$templateId': {
      id: '/_app/viral-studio/templates/$templateId'
      path: '/viral-studio/templates/$templateId'
      fullPath: '/viral-studio/templates/$templateId'
      preLoaderRoute: typeof AppViralStudioTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viral-studio/$id_/items/$itemId': {
      id: '/_app/viral-studio/$id_/items/$itemId'
      path: '/viral-studio/$id/items/$itemId'
      fullPath: '/viral-studio/$id/items/$itemId'
      preLoaderRoute: typeof AppViralStudioIdItemsItemIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClipsRoute: typeof AppClipsRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppBrandsBrandIdRoute: typeof AppBrandsBrandIdRoute
  AppViralStudioIdRoute: typeof AppViralStudioIdRoute
  AppViralStudioNewRoute: typeof AppViralStudioNewRoute
  AppViralStudioQueueRoute: typeof AppViralStudioQueueRoute
  AppBrandsIndexRoute: typeof AppBrandsIndexRoute
  AppViralStudioIndexRoute: typeof AppViralStudioIndexRoute
  AppViralStudioBrandsBrandIdRoute: typeof AppViralStudioBrandsBrandIdRoute
  AppViralStudioTemplatesTemplateIdRoute: typeof AppViralStudioTemplatesTemplateIdRoute
  AppViralStudioBrandsIndexRoute: typeof AppViralStudioBrandsIndexRoute
  AppViralStudioTemplatesIndexRoute: typeof AppViralStudioTemplatesIndexRoute
  AppViralStudioIdItemsItemIdRoute: typeof AppViralStudioIdItemsItemIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClipsRoute: AppClipsRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppBrandsBrandIdRoute: AppBrandsBrandIdRoute,
  AppViralStudioIdRoute: AppViralStudioIdRoute,
  AppViralStudioNewRoute: AppViralStudioNewRoute,
  AppViralStudioQueueRoute: AppViralStudioQueueRoute,
  AppBrandsIndexRoute: AppBrandsIndexRoute,
  AppViralStudioIndexRoute: AppViralStudioIndexRoute,
  AppViralStudioBrandsBrandIdRoute: AppViralStudioBrandsBrandIdRoute,
  AppViralStudioTemplatesTemplateIdRoute:
    AppViralStudioTemplatesTemplateIdRoute,
  AppViralStudioBrandsIndexRoute: AppViralStudioBrandsIndexRoute,
  AppViralStudioTemplatesIndexRoute: AppViralStudioTemplatesIndexRoute,
  AppViralStudioIdItemsItemIdRoute: AppViralStudioIdItemsItemIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
